### PR TITLE
Expanding grid overlay feature to rotation mode

### PR DESCRIPTION
**Pull request by MarinnaCole**
I have added this to the original implementation so now crop window can display different grid layout even during rotation. Note Fibonacci is known to be still broken (hence it is still disabled under rotation mode) and this is on TODO list to fix.

### CODE REVIEW

**Comment by MarinnaCole** [comment]
Just added the last piece of this work. Now grid overlay is full functional under rotation mode.

**Comment by ktgw0316** [comment]
This works fine in Crop mode. Now I can rotate any kind of grids if I drag outside of the crop bounds. :+1: 

In the Rotate mode, I could change origin of rotation grid when I click on the grid in previous versions and it was useful when I want to rotate the grid lines to match vertical/horizontal lines, but it is not possible now. IMHO it would be better idea to keep the Rotate mode as-is and show the new grid patterns only in the Crop mode. I'm going to push a commit for this later.

**Comment by MarinnaCole** [comment]
I think one way to do this is when starting the rotate mode the display automatically turn back to the grid. Once the mouse is released (the user feels the rotation is ok) then the display can get to change again to different overlay to see whether it works for other composition. This should be a very easy change.

**Comment by ktgw0316** [comment]
@MarinnaCole Yes, it is very easy (and it's what the Crop mode was in v4.1.5), but what I'm talking about is a different thing. Could you build eb1ce40 and try its Rotation mode (with  button, not with  button)?  A picture is worth a thousand words of my poor explanation. The origin of rotation is marked with a circle for clarity in this commit, and I think you will understand what I'm trying to explain when you click somewhere inside the crop bounds then rotate the grid with mouse dragging.

**Pull request merged**
